### ISSUE TITLE
container.getMaskBBSize().length can be larger than 3 in CostesSignificanceTest

### ISSUE THREAD

**Issue by burgerga** [fiji/Colocalisation_Analysis#6]
(Fiji Is Just) ImageJ 2.0.0-rc-29/1.49s; Java 1.6.0_24 [64-bit]; Linux 3.13.0-49-generic; 1501MB of 2257MB (66%)
 
java.lang.ArrayIndexOutOfBoundsException: 3
	at algorithms.CostesSignificanceTest.execute(CostesSignificanceTest.java:99)
	at Coloc_2.colocalise(Coloc_2.java:447)
	at Coloc_2.run(Coloc_2.java:160)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:64)
	at java.lang.Thread.run(Thread.java:662)

**Comment by tomka** [comment]
Thanks for reporting. I'll be able to look into this next week. Do you by any chance have small sample images that trigger this (since I am not able to reproduce)?

**Comment by burgerga** [comment]
Unfortunately, I can't give you the real file I worked with. Instead I will give you a modified version where I set all pixel values to 1 and then cropped the image to a reasonable size, you can find it here: https://gist.github.com/burgerga/db94e602aa67b93bcc3d#file-synthetic_small-ome

Steps to reproduce:
- Open in Fiji
- Image > Color > Split channel
- Analyze > Colocalization -> Coloc 2
    - Unselect all algorithms except "Costes' Significance Test"
    - Press OK

**Comment by chalkie666** [comment]
time series data will trigger this bug
eg sample images - mitosis.tif
it makes no sense to do analysis on a time series... each time point must be analysed separately. So we should detect if imagej says the image is a time series, warn the user and quit. Or process each timepoint separately and set the jobName for each timepoint accordingly for the results. THe latter is probably what the naive user expects. 

(you could imagine doing a correlation measurement between different time points of the same colour channel.... then the images would need to be shuffled in dimensions appropriately, or a fancy input GUI created to select which dimensions to correlate against which...)
