### ISSUE TITLE
java.lang.NoClassDefFoundError: com/itextpdf/text/BadElementException

### ISSUE THREAD

**Issue by pawlowska** [fiji/Colocalisation_Analysis#66]
I tried Coloc2 for the first time today in 2 different computers. On both I get this error after the window where I select images and algorithms: 

`(Fiji Is Just) ImageJ 2.0.0-rc-43/1.51i; Java 1.6.0_24 [64-bit]; Windows 7 6.1; 62MB of 6059MB (1%)
 
java.lang.NoClassDefFoundError: com/itextpdf/text/BadElementException
	at Coloc_2.colocalise(Coloc_2.java:441)
	at Coloc_2.run(Coloc_2.java:172)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.ClassNotFoundException: com.itextpdf.text.BadElementException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	... 7 more
`

(the other computer is running Imagej 1.51p)

**Comment by imagejan** [comment]
You're still running on Java 1.6.0 (Java 6). Please make sure you're running on Java 8 and then enable the Java-8 update site.
See http://imagej.net/2016-05-10_-_ImageJ_HOWTO_-_Java_8,_Java_6,_Java_3D#Upgrading_an_old_installation

**Comment by pawlowska** [comment]
thanks, this helped. I thought I had both my ImageJ and Java up to date, but was not aware of these additional manual steps.
